<style>
    .ce-block__content,
    .ce-toolbar__content {
        max-width: unset !important;
    }
</style>
<head>
    <link href="/assets/Manage/css/editorjs/components/header/index.css" rel="stylesheet"/>
</head>
<div class="container container-fluid border" style="background-color:white;">
    <div id="editorjs" style="background-color:white;" class="px-4 py-3"></div>
</div>
<script src="https://cdn.jsdelivr.net/npm/@editorjs/header@latest"></script>
<script src="/assets/Manage/js/editorjs/editor.js"></script>
<script>
    const editor = new EditorJS({
        /**
         * Id of Element that should contain Editor instance
         */
        holder: 'editorjs',
        tools: {
            header: Header,
            paragraph: {
                config: {
                    placeholder: 'Tell your story...'
                }
            }
        }
    });
</script>