<div class="container">
<div class="row flex-lg-nowrap">
    <div class="col-12 col-lg-auto mb-3" style="width: 200px;">
        <div class="card p-3">
            <div class="e-navlist e-navlist--active-bg">
                <ul class="nav">
                    <li class="nav-item"><a class="nav-link px-2 %p_bookings%" href="/my-account"><span>My Bookings</span></a></li>
                    <li class="nav-item"><a class="nav-link px-2 %p_profile%" href="/my-account/profile"><i class="fa fa-fw fa-th mr-1"></i><span>Profile</span></a></li>
                    <li class="nav-item"><a class="nav-link px-2 %p_settings%" href="/my-account/settings"><i class="fa fa-fw fa-cog mr-1"></i><span>Settings</span></a></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="row">
            %html%
            <!---->
                </div>

            </div>
            <div class="col-12 col-md-3 mb-3 order-first order-md-3">
                <div class="card mb-3">
                    <div class="card-body">
                        <div class="px-xl-3">
                            <a class='btn btn-secondary float-right' href='/auth/logout'>
                                <i class="fa fa-sign-out"></i>
                                <span>Logout</span>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="card d-none d-md-block">
                    <div class="card-body">
                        <h6 class="card-title font-weight-bold">Support</h6>
                        <p class="card-text">Get fast, free help from our friendly assistants.</p>
                        <button type="button" class="btn btn-primary">Contact Us</button>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>