<head>
    <link href="/assets/Manage/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
</head>
<div class="container-fluid">

          <!-- Page Heading -->
            <h1 class="h3 mb-0 text-gray-800">Films</h1>
            <p class="mb-4">Below you will find all films for your cinema.</p>

            <div class="card shadow mb-4">
                <div class="card-header py-4" style="line-height:2;">
                    <h6 class="d-inline m-0 font-weight-bold text-primary">Films</h6>
                    <button onclick="Cinema.newFilm();" class="d-inline float-right btn btn-success btn-icon-split btn-sm">
                        <span class="icon text-white-50"><i class="fas fa-plus"></i></span>
                        <span class="text">Add film</span>
                    </button>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered dataTable" width="100%" id="dataTable">
                            <thead>
                                <th>Id</th>
                                <th>Film name</th>
                                <th class='d-none d-sm-table-cell'>Upcoming showings</th>
                                <th>Settings</Th>
                            </thead>
                            <tbody>
                                <?php print $data["films"];?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
</div>
        <!-- /.container-fluid -->


<script src="/assets/Manage/vendor/datatables/jquery.dataTables.min.js"></script>
<script src="/assets/Manage/vendor/datatables/dataTables.bootstrap4.min.js"></script>
<script>
    // Call the dataTables jQuery plugin
    $(document).ready(function() {
        $('#dataTable').DataTable();
    });
</script>