        <form id="newShowing" action="/Manage/ajax/films/{filmId}/addShowing" method="POST">
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <label for="showDate">Show date</label>
                        <input name="showDate" id="showDate" type="text" class="form-control" placeholder="Select date" autocomplete="off">
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <label for="showTime">Show time</label>
                        <input name="showTime" id="showTime" type="text" class="form-control" placeholder="Select time" autocomplete="off">
                    </div>
                </div>
            </div>
            <div class="form-group mb-2">
            <label for="screenSelect">Screen</label>
            <select id="screenSelect" class="screenSelect" name="screenSelection">
                {screens}
            </select>
            </div>
            <div class="form-group mb-2">
            <label for="ticketSelect">Available ticket options</label>
            <select id="ticketSelect" class="ticketSelect" multiple name="ticketSelection[]">
                {ticketTypes}
            </select>
            </div>
            <div class="form-group">
            <label for="special">Special Requirements</label>
                <textarea id="special" class="form-control" name="requirements"></textarea>
            </div>
            <button type="button" onclick="Cinema.submitAddShowing()" id="newShowSubmit" class="btn btn-success btn">Add</button>
        </form>
        <script>$('#showDate').datepicker({
            startView: 2,
            format: "dd-mm-yyyy",
            todayHighlight: true,
            disableTouchKeyboard: true,
            autoclose: true
        });
        $('#showTime').timepicker({
            'step': 10,
            'scrollDefault': '08:00',
            'timeFormat': 'H:i'
        });
        
       var ticketSelect = new SlimSelect({
       select: '.ticketSelect',
       closeOnSelect: false,
       placeholder: "Select ticket types"
        });
        
        var screenSelect = new SlimSelect({
       select: '.screenSelect',
       placeholder: "Select screen",
       showSearch: false
        });
        </script>