<div class="row p-3" style="min-height:150px;">
    <div class="col-12 col-sm-3 col-md-2">
        <img class="img-fluid img-round-corner film-thumb" src="%THUMBNAIL%"/>
    </div>
    <div class="col-12 col-sm-9 col-md-10 px-3 py-1">
        <h3 class="mt-2 mt-sm-0"><a href='/film/%FILMID%' class="h3">%FILMNAME%</a></h3>
        <p class="film-description">%FILMDESC%</p>
        <a href="/film/%FILMID%">Full synopsis ></a>
        <div class="row mt-2">
            <div class='col-sm-9 col-md-8'>
                <h6>Showtimes</h6>
                %SHOWTIMES%
            </div>
            <div class='col-md-4 col-sm-3 mt-4 mt-sm-0'>
                %RUNTIME% mins <span class='film-certificate p-2'>%RATING%</span>
            </div>
        </div>
    </div>
</div>
<hr/>