<div class="carousel-item %FIRST% film-hero film-banner banner-dark text-white" style="min-height: 534px;
background-image: url('%BANNER%');
background-repeat: no-repeat;
background-size: cover;
background-color: black;
border-radius: 0px;
text-shadow:4px 2px 4px black;">
            <div class="container container-fluid film-banner-inner px-5 px-md-2">
                <p class="h2 display-4 pt-5 mt-5 pt-sm-3 align-middle">%NAME%</p>
                <p class="lead align-middle">%DESC%</p>
                %BTN%
            </div>
</div>
