<div class="container-fluid">
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/Manage/settings">Settings</a></li>
        <li class="breadcrumb-item"><a href="/Manage/settings"><?php print $data["bc_mod"];?></a></li>
        <li class="breadcrumb-item active" aria-current="page"><?php print $data["bc_setting"];?></li>
    </ol>
</nav>
<?php print $data["html"];?>
</div>
