<ul class="list-group" style="font-size:18px;">
    <li class="list-group-item text-uppercase"><span class="font-weight-bold">FILM:</span> {FILM}</li>
    <li class="list-group-item text-uppercase"><span class="font-weight-bold">DATE:</span> {DATE}</li>
    <li class="list-group-item"><span class="font-weight-bold">TIME:</span> {TIME}</li>
    <li class="list-group-item text-uppercase"><span class="font-weight-bold">SCREEN:</span> {SCREEN}</li>
    <li class="list-group-item"><span class="font-weight-bold">ADMITS:</span> [{ADMITS_TOTAL}] - {ADMITS}</li>
    <li class="list-group-item text-uppercase"><span class="font-weight-bold">BOOKED BY:</span> {BOOKER}</li>
    <li class="list-group-item d-none d-md-block"><a class="btn btn-info" href="{BOOKING_LINK}">Manage Booking</a></li>
</ul>