<div class="jumbotron text-white pl-4 pl-md-5" style="min-height: 462px;
background-image: url('https://wellingtonorbit.co.uk/wp-content/uploads/2019/07/isnJGDrfR9dIrHMsPTvHtJaGEpc.jpg');
background-repeat: no-repeat;
background-size: cover;
background-color: black;
border-radius: 0px;
text-shadow:4px 2px 4px black;">
    <div class="container container-fluid">
        <p class="h2 display-4 pt-5 mt-5 pt-sm-3 align-middle">Rocketman</p>
        <p class="lead align-middle">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p>
        <button class='btn btn-light' style='border-radius:20px'>PLAY TRAILER</button>
        <br/>
        <a class='text-white pt-5' href="/">< Back to what's on</a>
    </div>
</div>
<div class="container container-fluid">
    <p>Rocketman</p>
    <hr/>
    <div class="row">
        <div class="col-sm-5">
            <img style="border-radius: 3px; margin-bottom: 3em;" src="https://theroxy.org/appimages/us/custom/WELORB/fisherman's friends.jpg" alt="Fisherman’s Friends" class="poster">
        </div>
        <div class="col-sm-7 p-3">
            <p>Ten fisherman from Cornwall are signed by Universal Records and achieve a top ten hit with their debut album of Sea Shanties. Based on the true-life story of Cornish folk band, Fisherman's Friends.</p>
            <ul>
                <li><i>RELEASED</i> 17/07/2019</li>
            </ul>
        </div>
    </div>
</div>