<div class="jumbotron text-white pl-4 pl-md-5 film-banner film-banner-small banner-dark" style="min-height: 534px;
background-image: url('<?php print $data["banner"]; ?>');
background-repeat: no-repeat;
background-size: cover;
background-color: black;
border-radius: 0px;
text-shadow:4px 2px 4px black;">
    <div class="container container-fluid film-banner-inner">
        <p class="h2 display-4 pt-4 pt-md-1 mt-4 mt-md-1 align-middle"><?php print $data["_title"]; ?></p>
        <?php if(strlen($data['trailer']) >= 1) {?><button type="button" onclick="Cinema.openTrailer('<?php print $data["trailer"]; ?>');" class='btn btn-light my-3' style='border-radius:20px; text-shadow:none;'>
                PLAY TRAILER
            </button><?php }?>
        <br/>
        <a class='text-white mt-5' href="/">< Back to what's on</a>
    </div>
</div>
<div class="container container-fluid">
    <p><?php print $data["_title"]; ?></p>
    <hr/>
    <div class="row">
        <div class="col-sm-5 d-none d-sm-block">
            <img style="border-radius: 3px; margin-bottom: 3em; max-height:600px;" src="<?php print $data["thumbnail"]; ?>" alt="<?php print $data["_title"]; ?>" class="poster img-fluid">
        </div>
        <div class="col-sm-7 p-3">
            <p><?php print $data["desc"]; ?></p>
            <ul class="movie-points">
                <li><i>RELEASED</i><?php print $data["release"]; ?></li>
                <li><i>CERTIFICATE</i><?php print $data["rating"]; ?></li>
                <li><i>RUNNING TIME</i><?php print $data["runtime"];?> mins</li>
            </ul>
            <h5>Showtimes</h5>
            <hr class="mt-0"/>
            <div class="mb-1">
                <?php print $data["showtimes"]; ?>
            </div>
            <hr/>
            <p class="small">More showings will be added in the coming weeks</p>
        </div>
    </div>
</div>