    <div class="container-fluid px-0 mt-5 align-middle" style="min-height:58vh;" id="page-content">
        <div class="container container-fluid align-middle">
            <h1 class="text-center py-5">404 Not Found</h1>
            <p class="text-center py-1">The page you are looking for doesn't exist. Please try again or click below to return home.</p>
            <p class="text-center py-1"><a href="/">Go back</a></p>
        </div>
    </div>
