    <div class="footer-dark">
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-md-3 item">
                        <h3>##SYSTEMTITLE##</h3>
                        <ul>
                            <li><a href="#">Home</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-6 col-md-3 item">
                        <h3>About</h3>
                        <ul>
                            <li><a href="#">What do we do</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6 item text">
                        <h3>GFC Cinemas</h3>
                        <p>Gadgetfreak cinemas is a custom cinema platform which allows any cinema to easily allow customers to book their tickets online.&nbsp;</p>
                    </div>
                </div>
                <p class="copyright">Gadgetfreak © 2019</p>
            </div>
        </footer>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/js/bootstrap.bundle.min.js"></script>
</body>

</html>