<head>
    <link href="/assets/Manage/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
</head>
<div class="container-fluid">

          <!-- Page Heading -->
            <h1 class="h3 mb-0 text-gray-800">Bookings</h1>
            <p class="mb-4">Below you will find all bookings made for your cinema.</p>

            <div class="card shadow mb-4">
                <div class="card-header py-4" style="line-height:2;">
                    <h6 class="d-inline m-0 font-weight-bold text-primary">Bookings</h6>
                    <button onclick="alert('coming soon');" class="d-inline float-right btn btn-success btn-icon-split btn-sm disabled">
                        <span class="icon text-white-50"><i class="fas fa-plus"></i></span>
                        <span class="text">New booking</span>
                    </button>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered dataTable" width="100%" id="dataTable" data-order='[[ 0, "desc" ]]'>
                            <thead>
                                <th>Date</th>
                                <th>Id</th>
                                <th>Film</th>
                                <th>Total</th>
                                <th>status</th>
                                <th>Settings</Th>
                            </thead>
                            <tbody>
                                <?php print $data["bookings"];?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
</div>
        <!-- /.container-fluid -->


<script src="/assets/Manage/vendor/datatables/jquery.dataTables.min.js"></script>
<script src="/assets/Manage/vendor/datatables/dataTables.bootstrap4.min.js"></script>
<script>
    // Call the dataTables jQuery plugin
    $(document).ready(function() {
        $('#dataTable').DataTable();
    });
</script>