<form id="resendConfirmation" action="/Manage/ajax/bookings/{id}/resendConfirmation" method="POST">
    <div class="form-group">
        <label for="inputEmail">Email</label>
        <input type="email" name="email" class="form-control" id="inputEmail" value="{email}" placeholder="Enter email">
    </div>
    <button type="button" onclick="Cinema.resendConfirmationEmail('submit', '{id}');" id="resendSubmit" class="btn btn-primary btn-block">Send</button>
</form>
<div class='Bkloader text-center mb-5 mt-5' style="display:none;">
    <div class="spinner-grow text-secondary" style="width: 4rem; height: 4rem;" role="status">
        <span class="sr-only">Loading...</span>
    </div>
    <h5 class="mt-5">Processing...</h5>
</div>