<head>
    <link rel="stylesheet" href="/assets/css/seat_layout.css">
</head>
<div id="MPstep1" class="container">
    <p>Choose an alternative showing from the list below</p>
    <div class="list-group">
        {items}
    </div>
</div>
<div id="MPstep2" class="container" style="display:none;">
        <div class="m-1">
            <button id="MPstep2Back" class="btn btn-info float-left">< Back</button>
        </div>
    <div class="screen-container text-center mx-auto m-0 m-md-5">
        <small><span class="h5">Select seats (<span id="selectionCount">0</span>/<span id="selectionAllowed">4</span>)</span><br/>
        Original seats: <span id="originalSeats">A1, A2, A3, A4</span></small>
        <table class="screen mx-auto" style="max-width:500px;">
            <tbody>
            </tbody>
        </table>
        <button id="MPstep2Confirm" class="btn btn-block btn-outline-success my-2">Confirm selection</button>
    </div>
</div>
<div class='Bkloader text-center mb-5 mt-5' style="display:none;">
    <div class="spinner-grow text-secondary" style="width: 4rem; height: 4rem;" role="status">
        <span class="sr-only">Loading...</span>
    </div>
    <h5 class="mt-5">Processing...</h5>
</div>
<script src="/assets/js/Seatpicker.js"></script>