<head>
    <link rel="stylesheet" href="/assets/css/seat_layout.css">
</head>
    <div class="screen-container text-center mx-auto my-3 m-0 m-md-5">
        <h1>Select your seat</h1>
        <table class="screen mx-auto">
            <tbody>
            <?php print $data["seats"]; ?>
            <tr class="screen-row">
                <td colspan='10' style="border:1px solid lightgrey; width:100%;" class="text-center p-1">SCREEN</td>
            </tr>
                <!--<tr class="screen-row">
                    <td class="screen-seat seat-standard">
                        <img src="https://www.jack-roe.co.uk/static/sales/images/seats/1-seat_GREY.png"/>
                        <br/>
                        A1
                    </td>
                    <td class="screen-seat seat-standard">
                        <img src="https://www.jack-roe.co.uk/static/sales/images/seats/1-seat_GREY.png"/>
                        <br/>
                        A2
                    </td>
                    <td class="screen-seat seat-standard">
                        <img src="https://www.jack-roe.co.uk/static/sales/images/seats/1-seat_GREY.png"/>
                        <br/>
                        A3
                    </td>
                    <td class="screen-seat seat-standard">
                        <img src="https://www.jack-roe.co.uk/static/sales/images/seats/1-seat_GREY.png"/>
                        <br/>
                        A4
                    </td>
                    <td class="screen-seat seat-standard">
                        <img src="https://www.jack-roe.co.uk/static/sales/images/seats/1-seat_GREY.png"/>
                        <br/>
                        A5
                    </td>
                    <td class="screen-seat seat-standard">
                        <img src="https://www.jack-roe.co.uk/static/sales/images/seats/1-seat_GREY.png"/>
                        <br/>
                        A6
                    </td>
                    <td class="screen-seat seat-standard">
                        <img src="https://www.jack-roe.co.uk/static/sales/images/seats/1-seat_GREY.png"/>
                        <br/>
                        A7
                    </td>
                    <td class="screen-seat seat-double">
                        <img src="https://www.jack-roe.co.uk/static/sales/images/seats/2-seat_GREY.png"/>
                        <br/>
                        A8,9
                    </td>
                    <td class="screen-seat seat-standard">
                        <img src="https://www.jack-roe.co.uk/static/sales/images/seats/1-seat_GREY.png"/>
                        <br/>
                        A10
                    </td>
                </tr>-->
            </tbody>
        </table>
    </div>