<head>
    <link rel="stylesheet" href="/assets/css/seat_layout.css">
</head>
    <div class="container container-fluid my-5">
        <div class="mx-auto stepwizard col-md-offset-3 d-none d-sm-table">
            <div class="stepwizard-row setup-panel">
                <div class="stepwizard-step">
                    <a href="#step-1" class="btn btn-success btn-circle">1</a>
                    <p>Select tickets</p>
                </div>
                <div class="stepwizard-step">
                    <a href="#step-2" class="btn btn-primary btn-circle" disabled="disabled">2</a>
                    <p>Select seats</p>
                </div>
                <div class="stepwizard-step">
                    <a href="#step-3" class="btn btn-secondary btn-circle" disabled="disabled">3</a>
                    <p>Enter details</p>
                </div>
                <div class="stepwizard-step">
                    <a href="#step-4" class="btn btn-secondary btn-circle" disabled="disabled">4</a>
                    <p>Review basket</p>
                </div>
            </div>
        </div>

    <div class="card">
        <div class="card-header">
            <p>Please select your seats for:</p>
            <p style="font-weight:bold;">Rocketman (15) at 10:30 on MONDAY 10TH JULY 2019 showing in Screen 1</p>
            <p style="font-weight:bold;">Available seats: <span>24</span></p>
        </div>
        <div class="card-body">
            <div class="screen-container text-center mx-auto m-0 m-md-5">
                <h1>Select your seat</h1>
                <table class="screen mx-auto">
                    <tbody>
                    <?php print $data["seats"]; ?>
                    <tr class="screen-row">
                        <td colspan='10' style="border:1px solid lightgrey; width:100%;" class="text-center p-1">SCREEN</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>