<div class="jumbotron text-white pl-4 pl-md-5" style="min-height: 462px;
background-image: url('https://wellingtonorbit.co.uk/wp-content/uploads/2019/07/isnJGDrfR9dIrHMsPTvHtJaGEpc.jpg');
background-repeat: no-repeat;
background-size: cover;
background-color: black;
border-radius: 0px;
text-shadow:4px 2px 4px black;">
    <div class="container container-fluid">
        <p class="lead align-middle">Your booking tickets for:</p>
        <p class="h2 display-4 pt-1 mt-1 pt-sm-1 align-middle">Rocketman</p>
        <p class="lead align-middle">On monday 10th July at 10:30</p>
        <br/>
        <a class='text-white pt-5' href="/">< Back to what's on</a>
    </div>
</div>
<div class="container container-fluid mb-5">
    <div class="mx-auto stepwizard col-md-offset-3 d-none d-sm-table">
        <div class="stepwizard-row setup-panel">
            <div class="stepwizard-step">
                <a href="#step-1" class="btn btn-primary btn-circle">1</a>
                <p>Select tickets</p>
            </div>
            <div class="stepwizard-step">
                <a href="#step-2" class="btn btn-secondary btn-circle" disabled="disabled">2</a>
                <p>Select seats</p>
            </div>
            <div class="stepwizard-step">
                <a href="#step-3" class="btn btn-secondary btn-circle" disabled="disabled">3</a>
                <p>Enter details</p>
            </div>
            <div class="stepwizard-step">
                <a href="#step-4" class="btn btn-secondary btn-circle" disabled="disabled">4</a>
                <p>Review basket</p>
            </div>
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            <p>Please select tickets for:</p>
            <p style="font-weight:bold;">Rocketman (15) at 10:30 on MONDAY 10TH JULY 2019 showing in Screen 1</p>
            <p style="font-weight:bold;">Available seats: <span>24</span></p>
        </div>
        <div class="card-body">
            <table class="table">
                <thead>
                    <th>Selection</th>
                    <th class="text-right">Price</th>
                    <th>Qty</th>
                    <th class="d-none d-sm-table-cell text-right">Subtotal</th>
                </thead>
                <tbody>
                <?php print $data["tickets"]; ?>
                    <!--<tr>
                        <td class="col-8 col-sm-10 col-md-9">Adult</td>
                        <td class="col-1 col-sm-1 col-md-1 text-right">&pound;8.00</td>
                        <td class="col-3 col-sm-1 col-md-2 text-right">
                            <select class="form-control input-sm" style="width:65px;">
                                <option value="0">0</option>
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                            </select>
                        </td>
                        <td class="col-1 col-md-1 text-right d-none d-sm-table-cell"></td>
                    </tr>
                    <tr>
                        <td class="col-8 col-sm-10 col-md-9">Child
                            <div>
                                <small class="text-secondary">Proof of entitlement may be required</small>
                            </div>
                        </td>
                        <td class="col-1 col-sm-1 col-md-1 text-right">&pound;6.00</td>
                        <td class="col-3 col-sm-1 col-md-2 text-right">
                            <select class="form-control input-sm" style="width:65px;">
                                <option value="0">0</option>
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                            </select>
                        </td>
                        <td class="col-1 col-md-1 text-right d-none d-sm-table-cell"></td>
                    </tr>
                    <tr>
                        <td class="col-8 col-sm-10 col-md-9">Concession/OAP
                            <div>
                                <small class="text-secondary">Proof of entitlement may be required</small>
                            </div>
                        </td>
                        <td class="col-1 col-sm-1 col-md-1 text-right">&pound;7.00</td>
                        <td class="col-3 col-sm-1 col-md-2 text-right">
                            <select class="form-control input-sm" style="width:65px;">
                                <option value="0">0</option>
                                <option value="1">1</option>
                                <option value="2" selected>2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                            </select>
                        </td>
                        <td class="col-1 col-md-1 text-right d-none d-sm-table-cell"></td>
                    </tr>-->
                </tbody>
            </table>
        </div>
        <div class="card-body">
            <strong>2 tickets selected at a total cost of &pound;14.00</strong>
        </div>
    </div>
        <a href="/booking/new/seats" class="btn btn-block text-center mt-2 p-3 btn-outline-secondary">Next</a>
</div>