<div class="jumbotron text-white pl-4 pl-md-5 film-banner banner-dark mb-0" style="min-height: 534px;
    background-image: linear-gradient(#000 10%);
    background-repeat: no-repeat;
    background-size: cover;
    background-color: black;
    border-radius: 0px;
    text-shadow:4px 2px 4px black;">
    <div class="container container-fluid pt-5 mt-5 text-center film-banner-inner">
        <h1>View Booking</h1>
        <p class="lead align-middle mt-3">Please provide your booking ID & Email to view your booking</p>
        <form class="form mx-auto" style="max-width:700px; text-align:center;" method="POST">
                <input class="form-control form-control-lg mt-2 mx-auto" type="text" name="bookingId" placeholder="Booking ID" style="max-width:300px;" required/>
                <input class="form-control form-control-lg mt-2 mx-auto" type="email" name="bookingEmail" placeholder="Email" style="max-width:300px;" required/>
                <button class="btn btn-lg btn-outline-light mx-auto mt-4" type="submit">View Booking</button>
        </form>
    </div>
</div>