<div class="card shadow mb-4">
    <div class="card-header py-4" style="line-height:2;">
        <h6 class="d-inline m-0 font-weight-bold text-primary">Configure Email</h6>

    </div>
    <div class="card-body">
        <div id="alertBanner" class="alert alert-danger text-center alert-dismissible fade show d-none" role="alert">
            <span id="alert-message"></span>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <form id="emailForm" class="needs-validation" autocomplete="off" novalidate>
            <button id="testBtn" class="btn btn-sm btn-info my-2" type="submit" data-cmd="test">Test Connection</button>
            <div class="form-row">
                <div class="form-group col-md-8">
                    <label for="inputEmail4">Host(server)</label>
                    <input type="text" class="form-control" name="host" id="inputEmail4" placeholder="mail.myserver.co.uk" autocomplete="off" minlength="3" value="%HOST%" required>
                </div>
                <div class="form-group col-md-4">
                    <label for="inputPassword4">Port</label>
                    <input type="number" class="form-control" name="port" id="inputPassword4" min="1" maxlength="5" max="65335" autocomplete="off" minlength="3" value="%PORT%" required>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-12">
                    <label for="inputEmail4">Email</label>
                    <input type="email" class="form-control" name="account" id="inputEmail4" placeholder="noreply@myserver.co.uk" autocomplete="off" value="%ACCOUNT%" required>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="inputPassword4">Username</label>
                    <input type="text" class="form-control" name="username" id="inputPassword4" required autocomplete="off" required value="%USERNAME%" minlength="3">
                </div>
                <div class="form-group col-md-6">
                    <label for="inputPassword4">Password</label>
                    <input type="password" class="form-control" name="password" id="inputPassword4" autocomplete="new-password">
                    <small class="form-text text-info">For security, we won't display the current password here but you can update it by populating this field.</small>
                </div>
            </div>
        </form>
    </div>
</div>
<script>
    (function() {
        'use strict';
        window.addEventListener('load', function() {
            // Fetch all the forms we want to apply custom Bootstrap validation styles to
            var forms = document.getElementsByClassName('needs-validation');
            // Loop over them and prevent submission
            var validation = Array.prototype.filter.call(forms, function(form) {
                form.addEventListener('submit', function(event) {
                    $("#alertBanner").addClass("d-none");
                    event.preventDefault();
                    event.stopPropagation();

                    if (form.checkValidity() === false) {

                        $("#alert-message").html("Please ensure all fields are correct.");
                        $("#alertBanner").removeClass("d-none");

                    } else {

                        var loader = "<div id='loader' class='text-center my-3'><div class='spinner-grow text-secondary' style='width: 4rem; height: 4rem;' role='status'>" +
                            "<span class='sr-only'></span></div><h5 class='mt-5'>Connecting...</h5></div></div>";

                        showModal("Test Connection", loader, {vcenter: true, size: "md"});

                        $.ajax({
                            url: "/Manage/settings/email/test",
                            method: "POST",
                            data: $("#emailForm").serialize(),
                            success: function(res) {

                                if(res.status == 200) {

                                    updateModal("<h4 class='text-success'>Success</h4><p>Email configuration works and you should receive a test email.</p>");
                                    $("#testBtn").html("Connection success.").removeClass("btn-info").addClass("btn-success disabled").attr("disabled", "disabled");
                                }

                            },
                            error: function(err) {

                                let error = JSON.parse(err.responseText);

                                updateModal("<h4 class='text-danger'>Failed</h4><hr/><p style='font-size: 13px;'>" + error.error_desc + "</p>");

                            }
                        });

                    }

                    form.classList.add('was-validated');
                }, false);
            });
        }, false);
    })();
</script>