<form action="/Manage/ajax/screens/new" method="POST">
    <div class="form-group">
    <label for="inputScreenName">Screen name</label>
    <input type="text" name="screenName" class="form-control" id="inputScreenName" placeholder="Enter screen name">
    <small class="form-text text-muted">The screen name will be displayed as 'Screen #NAME#' on the system</small>
  </div>
  <button type="button" id="newScreenSubmit" class="btn btn-primary btn-block">Create</button>
</form>