<head>
    <link href="/assets/Manage/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
</head>
<div class="container-fluid">

          <!-- Page Heading -->
            <a href='/Manage/screens' class="btn btn-info btn-sm mb-2"> < Back</a>
            <h1 class="h3 mb-0 text-gray-800"><?php print $data["_title"]; ?></h1>
            <p class="mb-4">Below you will find information regarding this screen.</p>

            <div class="card shadow mb-4">
                <div class="card-header">
                    <ul class="nav nav-tabs card-header-tabs">
                      <li class="nav-item">
                        <a class="nav-link <?php print (($data["op"] == "info") ? "active" : "");?>" href="/Manage/screens/<?php print $data["screen_id"];?>">Info</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link <?php print (($data["op"] == "layout") ? "active" : "");?>" href="/Manage/screens/<?php print $data["screen_id"];?>/layout">Layout</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link <?php print (($data["op"] == "shows") ? "active" : "");?>" href="#">Upcoming shows</a>
                      </li>
                    </ul>
                </div>
                <div class="card-body">
                        <?php print $data["html"]; ?>
                </div>
            </div>
</div>
        <!-- /.container-fluid -->


<script src="/assets/Manage/vendor/datatables/jquery.dataTables.min.js"></script>
<script src="/assets/Manage/vendor/datatables/dataTables.bootstrap4.min.js"></script>
<script>
    // Call the dataTables jQuery plugin
    $(document).ready(function() {
        $('#dataTable').DataTable();
    });
</script>