<style>
    .reset-container{
        background-color:#f8f8f8;
    }
</style>
<div class="container h-100 reset-container">
    <div class="row h-100">
        <div class="col-sm-10 col-md-8 col-lg-8 mx-auto d-table h-100">
            <div class="d-table-cell align-middle">

                <div class="text-center mt-4">
                    <h1 class="h2">Reset password</h1>
                    <p class="lead">
                        Enter your email to reset your password.
                    </p>
                </div>

                <div class="card">
                    <div class="card-body">
                        <div class="m-sm-4">
                            <form id="reset-form" method="POST" class="needs-validation" novalidate>
                                <div class="form-group">
                                    <label>Email</label>
                                    <input class="form-control form-control-lg" id="resetEmail" type="email" name="email" placeholder="Enter your email" required>
                                    <input type="hidden" value="%AUTHTOKEN%" name="auth"/>
                                    <div class="invalid-feedback">
                                        Please enter a valid email.
                                    </div>
                                </div>
                                <div class="text-center mt-3">
                                    <button id="resetSubmit" type="submit" class="btn btn-lg btn-primary">Send link</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>