<style>
    .reset-container{
        background-color:#f8f8f8;
    }
</style>
<div class="jumbotron text-white pl-4 mb-0 pl-md-5 film-banner film-banner-narrow banner-dark" style="min-height: 300px;
    background-image: url('');
    background-repeat: no-repeat;
    background-size: cover;
    background-color: black;
    border-radius: 0px;
    text-shadow:4px 2px 4px black;">
    <div class="container container-fluid film-banner-inner">
        <p class="h2 display-4 pt-4 pt-md-1 mt-4 mt-md-1 align-middle">Reset Password</p>
        <br/>
    </div>
</div>
<div class="container h-100 reset-container">
    <div class="row h-100">
        <div class="col-sm-12 col-md-6 col-lg-4 order-first order-md-last d-table middle-height mt-5">
            <div class="d-table-cell align-middle">
                <h3>Password Requirements</h3>
                <ul>
                    <li  id="pwdCheckminlen" class="text-danger">At least %minlen% characters in length.</li>
                    <li  id="pwdCheckmaxlen" class="text-danger">No more than %maxlen% characters in length.</li>
                    <li  id="pwdCheckcapitalchar" class="text-danger">At least one capital letter.</li>
                    <li  id="pwdChecknumber" class="text-danger">At least one number.</li>
                    <li  id="pwdChecklowerchar" class="text-danger">At least one lowercase letter.</li>
                    <li  id="pwdCheckspecialchar" class="text-danger">At least one special character.</li>
                    <li  id="pwdCheckMatch" class="text-danger">New passwords match.</li>
                </ul>
            </div>
        </div>
        <div class="col-sm-10 col-md-6 col-lg-8 mx-auto d-table h-100">
            <div class="d-table-cell align-middle middle-height">

                <div class="text-center mt-4">
                    <h1 class="h2">Reset password</h1>
                    <p class="lead">
                        Enter your new password below.
                    </p>
                </div>

                <div class="card">
                    <div class="card-body">
                        <div class="m-sm-4">
                            <form id="reset-form" method="POST" class="needs-validation" novalidate>
                                <div class="form-group">
                                    <label>New password</label>
                                    <input class="form-control form-control-lg" id="resetPwd" type="password" name="pwd1" placeholder="Enter new password" required>

                                    <div class="invalid-feedback">
                                        Please enter a valid password.
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Re-enter new password</label>
                                    <input class="form-control form-control-lg" id="resetPwd2" type="password" name="pwd2" placeholder="Re-enter new password" required>
                                    <input type="hidden" value="%AUTHTOKEN%" name="auth"/>
                                    <div class="text-center mt-3">
                                    <button id="resetSubmit" type="submit" class="btn btn-lg btn-primary disabled" disabled="disabled">Update Password</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
<script>
    Cinema.startValidatePasswordHandler(%REQUIREMENTS%);
</script>