<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php if(isset($data["_title"])) { print $data["_title"] . " | "; }?><?=$title?></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="/assets/css/Footer-Dark.css">
    <link rel="stylesheet" href="/assets/css/Navigation-Clean.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/assets/css/styles.css">
    <!-- Jquery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
    <!-- ICONS -->
    <script src="https://kit.fontawesome.com/9bb8a45ecf.js"></script>
    <script src="/assets/Manage/js/modal.js"></script>
    <script src="/assets/js/Cinema.js"></script>
</head>

<body class="sidebar-toggled" style="background-color:black;">
    <div id="page-header">
        <nav class="navbar navbar-dark fixed-top navbar-expand-md navigation-clean navbar-blackfade px-4 py-4" <!--style="background-color:rgb(40,45,50);-->">
            <div class="container-fluid"><a class="navbar-brand text-white" href="/"><?php print $data["__webTitle"];?></a><button class="navbar-toggler" data-toggle="collapse" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse navbar-bg" id="navcol-1">
                    <ul class="nav navbar-nav ml-auto">
                        <li class="nav-item" role="presentation"><a class="nav-link" href="/">What's On</a></li>
                        <li class="nav-item" role="presentation"><a class="nav-link" href="/my-account">My Account</a></li>
                        <li class="dropdown"><a class="dropdown-toggle nav-link dropdown-toggle" data-toggle="dropdown" aria-expanded="false" href="#">Dropdown </a>
                            <div class="dropdown-menu" role="menu"><a class="dropdown-item" role="presentation" href="#">First Item</a><a class="dropdown-item" role="presentation" href="#">Second Item</a><a class="dropdown-item" role="presentation" href="#">Third Item</a></div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <?php print notifications::display(2); ?>
    <div class="alert alert-info text-center mb-0 d-none"></div>
    <div style="background-color:#f8f8f8;">
        <div class="container-fluid px-0" id="page-content">
            <?=$content?>
        </div>
    </div>

        <footer class="footer-dark">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-md-3 item">
                        <h3><?php print $data["__webTitle"];?></h3>
                        <ul>
                            <li><a href="#">Home</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-6 col-md-3 item">
                        <h3>About</h3>
                        <ul>
                            <li><a href="#">What do we do</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6 item text">
                        <h3>GFC Cinemas</h3>
                        <p>Gadgetfreak cinemas is a custom cinema platform which allows any cinema to easily allow customers to book their tickets online.&nbsp;</p>
                    </div>
                </div>
                <p class="copyright">Gadgetfreak © 2019</p>
            </div>
        </footer>

    <script>
    
        $(function () {
            
            $('[data-toggle="tooltip"]').tooltip()
            
        });

        // Floating Navbar on scroll
        $(window).scroll(function() {

            //if I scroll more than 1000px...
            if($(window).scrollTop() > 100){

                $("nav").addClass("navbar-blackfade-scrolled").removeClass("py-4");

            } else {

                $("nav").removeClass("navbar-blackfade-scrolled").addClass("py-4");

            }
        });
        
    </script>
</body>

</html>