<div class="jumbotron text-white pl-4 pl-md-5 film-hero" style="min-height: 462px;
background-image: url('https://wellingtonorbit.co.uk/wp-content/uploads/2019/07/isnJGDrfR9dIrHMsPTvHtJaGEpc.jpg');
background-repeat: no-repeat;
background-size: cover;
background-color: black;
border-radius: 0px;
text-shadow:4px 2px 4px black;">
    <div class="container container-fluid">
        <p class="h2 display-4 pt-5 mt-5 pt-sm-3 align-middle">Rocketman</p>
        <p class="lead align-middle">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p>
        <button class='btn btn-light' style='border-radius:20px'>PLAY TRAILER</button>
    </div>
</div>
<div id="whats-on-categories" class="container container-fluid">
    <h1 class="mb-4">What's on</h1>
    <div id='mobileCateogries' class="row d-block d-sm-none">
        <div class='col-lg-4'>
            <span>Date</span>
            <select class='form-control' name='dateSelector'>
                <option value='test'>Test</option>
            </select>
        </div>
    </div>
    <div class="btn-group d-none d-sm-inline-flex" role="group" aria-label="Basic example">
        <button type="button" class="btn btn-outline-primary btn-underline active p-3">NOW PLAYING</button>
        <button type="button" class="btn btn-outline-primary btn-underline p-3">ADVANCED BOOKINGS</button>
        <button type="button" class="btn btn-outline-primary btn-underline p-3">NEW RELEASES</button>
    </div>
</div>
<div class="container container-fluid mt-3 mb-3">
    <div class="row p-3" style="min-height:150px;">
            <div class="col-12 col-sm-3 col-md-2">
                <img class="img-fluid img-round-corner film-thumb" src="https://theroxy.org/appimages/us/custom/WELORB/rocketman.jpg"/>
            </div>
            <div class="col-12 col-sm-9 col-md-10 px-3 py-1">
                <h3 class="mt-2 mt-sm-0"><a href='/film/rocketman' class="h3">Rocketman</a></h3>
                <p>The story of Elton John's life, from his years as a prodigy at the Royal Academy of Music through his influential and enduring musical partnership with Bernie Taupin.</p>
                <a href="Javascript:void(0);">Full synopsis ></a>
                <div class="row mt-2">
                    <div class='col-sm-9 col-md-8'>
                        <h6>Showtimes</h6>
                        <span class="pb-1">Wednesday 3rd July</span>
                        <br/>
                        <a href="/booking/new/rocketman/1562012473" class="btn btn-primary">10:30</a>
                        <button class="btn btn-primary">More showtimes ></button>
                    </div>
                    <div class='col-md-4 col-sm-3 mt-4 mt-sm-0'>
                        121 mins <span class='film-certificate p-2'>15</span>
                    </div>
                </div>
            </div>
    </div>
    <hr/>
    <div class="row p-3" style="min-height:150px;">
            <div class="col-12 col-sm-3 col-md-2">
                <img class="img-fluid img-round-corner film-thumb" src="https://theroxy.org/appimages/us/custom/WELORB/rocketman.jpg"/>
            </div>
            <div class="col-12 col-sm-9 col-md-10 px-3 py-1">
                <h3 class="mt-2 mt-sm-0">Rocketman</h3>
                <p>The story of Elton John's life, from his years as a prodigy at the Royal Academy of Music through his influential and enduring musical partnership with Bernie Taupin.</p>
                <a href="Javascript:void(0);">Full synopsis ></a>
                <div class="row mt-2">
                    <div class='col-sm-9 col-md-8'>
                        <h6>Showtimes</h6>
                        <span class="pb-1">Wednesday 3rd July</span>
                        <br/>
                        <button class="btn btn-primary">10:30</button>
                        <button class="btn btn-primary">More showtimes ></button>
                    </div>
                    <div class='col-md-4 col-sm-3 mt-4 mt-sm-0'>
                        121 mins <span class='film-certificate p-2'>15</span>
                    </div>
                </div>
            </div>
    </div>
</div>