<?php print $data["banner"];?>
<div id="whats-on-categories" class="container container-fluid">
    <h1 class="mb-4">What's on</h1>
    <div id='mobileCateogries' class="row d-none d-sm-none">
        <div class='col-lg-4'>
            <span>Date</span>
            <select class='form-control' name='dateSelector'>
                <option value='test'>Test</option>
            </select>
        </div>
    </div>
    <div class="btn-group d-none d-sm-inline-flex" role="group" aria-label="Basic example">
        <button type="button" class="btn btn-outline-primary btn-underline active p-3">NOW PLAYING</button>
        <button type="button" class="btn btn-outline-primary btn-underline p-3">ADVANCED BOOKINGS</button>
        <button type="button" class="btn btn-outline-primary btn-underline p-3">NEW RELEASES</button>
    </div>
</div>
<div class="container container-fluid mt-3 mb-3">
    <?php print $data["films"];?>
</div>